### ISSUE TITLE
Error when deleting a question

### ISSUE THREAD

**Issue by damianstrain** [iionly/Elgg_1.8_faq#3] opened 2014-08-14 15:07 UTC
Clicking on the delete icon displays an Elgg system error message that says "faq:delete:error:invalid_object".

**Comment by iionly** [comment] 2014-08-14 16:28
Indeed, the "faq:delete:error:invalid_object" language string is missing in the language file resulting in the output of the raw string instead of the actual error message.

But this error message should normally only occur if the delete action is called with a GUID that does not belong to a FAQ object entitiy. A valid FAQ entry should be removed without this error happening.

So, does this error occur for you when trying to delete a valid FAQ? If yes, what version of the FAQ plugin are you using and had you installed an older version of the FAQ plugin before (older than version 1.8.3)? If you upgraded from an older version without disabling the FAQ plugin, it might help to do it now: disable the FAQ plugin, then enable it again and try again to delete the FAQ entry.

It would help me when trying to debug this issue, if you could answer my questions and tell me if the suggestion with disabling/re-enabling helps. As I said, the error should normally not occur if it's an FAQ you are trying to delete.

**Comment by damianstrain** [comment] 2014-08-14 18:46
Apologies, I should been more descriptive :). 

I am using version 1.8.5 of your plugin on a fresh install of Elgg v1.8.19. The error occurs when trying to delete a valid FAQ entry. I have tried disabling/re-enabling the plugin, and also flushed the cache.

Hope that helps.

**Comment by iionly** [comment] 2014-08-14 20:00
If it's a fresh install with FAQ v1.8.5 the disabling/re-enabling wouldn't have any effect anyway (I'd made some changes in an earlier version that I thought that it might have resulted in the error in your case even if it would be very unlikely).

The deletion error shouldn't occur on a valid FAQ - can't reproduce it at least. So, there might be some other reason it fails. Now the problem is to find out what it is.

Is it only one FAQ that fails to get removed or does the same problem happen with any FAQ you tried to delete? Is there anything wrong with the FAQ you want to delete apart from the problem with deletion? For example, does it show up correctly on your site or is there anything unusual about it like the answer not getting displayed? If something would look wrong on the site it might indicate that the FAQ's database entry is faulty for whatever reason resulting in the deletion failing because it's not seen as valid FAQ.

Are you trying to delete the FAQ using the same admin account used when creating it? Shouldn't make a difference but maybe worth trying if you indded have several admin accounts in use (additonally: are you using the roles plugin for adding some type of account with more rights than normal users?).

The problem might also be caused by some other 3rd party plugin installed on your site. Unfortunately, I can't check compatibility with all existing plugins. For testing you could temporarily disable all other 3rd party plugins to find out if deleting the FAQ works then. If it would get removed, it would show that another plugin is causing the problem. If it still does not work, then it would be obvious at least that no other plugin is involved.

**Comment by damianstrain** [comment] 2014-08-14 20:35
I created 6 FAQs in all and was unable to delete any of them. Also, 2 categories were created with 3 FAQs in each. All FAQs displayed correctly, questions and answers. The same admin account was used to create the FAQs and delete them. I am not using the Roles plugin. The only FAQ plugin setting I changed was for the FAQs to be publicly viewable.

No 3rd party plugins were installed, just a fresh install of Elgg v1.8.19 with all vanilla plugins and settings. The FAQ plugin was listed last in the plug-ins list.

I will try with all plug-ins disabled to see if that makes a difference, unfortunately I don't have my work laptop with me to test (Elgg is being rolled out in our enterprise). So I will try that scenario tomorrow in work.

**Comment by iionly** [comment] 2014-08-14 21:06
The bundled plugins are very likely not causing the problem.

You could try to re-install the FAQ plugin. Maybe some file was not completely copied correctly. Though I think this is also a very unlikely reason as the delete action is called (otherwise the error message wouldn't show up).

Is SSL enabled for the site (https)? What browser (version) are you using for testing? I suspect it might be a Javascript issue and in this case the browser used might be the problem. Could you test with another browser?

**Comment by damianstrain** [comment] 2014-08-14 21:41
SSL is not currently enabled on our dev environment. Browsers used for testing are the latest version of Chrome, and IE, versions 8 and up. I have not tested with Opera or Firefox.

Tomorrow I will drop the database and reinstall Elgg to see if the issue persists.

**Comment by damianstrain** [comment] 2014-08-15 10:04
Just tested with a clean database and Elgg v1.8.19 install. FAQs are being successfully deleted. Something may have become corrupt at some point with my install.

**Comment by iionly** [comment] 2014-08-17 13:00
Quite impossible to say what might have caused the issue with the database. As far as I can say, this problem couldn't have been caused by the FAQ plugin, so I'll close this issue for now.

I've just updated the repo with the missing language strings. Though you'll hopefully won't see them anymore now that deleting FAQs work.

**Closed as completed by iionly** 2014-08-17 13:00 UTC
